### ISSUE TITLE
How to remove Child cell and reload data without closing Parent

### ISSUE THREAD

**Issue by WebElg** [Vkt0r/AccordionSwift#23]
Is there a way to remove Child cell and reload data without closing Parent? When I reload data, Parent cell closes, and I need it to remain opened.

**Comment by Vkt0r** [comment]
@WebElg If when you remove the child you set the current state of the parent cell to expanded before reload the data source it should do the work. Please let me know if this help you

**Comment by Vkt0r** [comment]
Closing this. Please open it again if you feel your problem persist.
