### ISSUE TITLE
How to select a default parent and child cell

### ISSUE THREAD

**Issue by jiheneme** [Vkt0r/AccordionSwift#24]
Hello everyone,

I'm looking for a way to select a parent-child cell by default automatically after the tableView was loaded.

How can I do the equivalent of this:
self.tableView.selectRow(at: IndexPath.init(row: 2, section: 0), animated: false, scrollPosition: UITableViewScrollPosition.none)
using your library ?

Thanks in advance !

**Comment by Vkt0r** [comment]
Hi,

I'm afraid to support what do you want you need to extend the library, because the logic behind selection of cells, etc it's a little tricky. I hope this help you.

**Comment by Vkt0r** [comment]
@jiheneme See the new version of the library and let me know if helps you in something to achieve your goal.
