### ISSUE TITLE
Parent cells require children?

### ISSUE THREAD

**Issue by taberrr** [Vkt0r/AccordionSwift#32]
I wanted to be able to detect when the user selects a parent cell that doesn't have any children. In order to check for that, I had to make `Parent.childs` public, FYI.

**Edit:** it looks like handling taps on parent cells works now, thanks for the update! But it also seems that child cells aren't optional. My use case is a "Settings" row in a navigation that doesn't have any child cells.

**Comment by Vkt0r** [comment]
@taberrr See the new version of the library and let me know if works better for you.

**Comment by taberrr** [comment]
@Vkt0r I'm using 2.0 but when I make GroupA in the example have an empty Array for its childs: property, I get this error: [img]https://i.imgur.com/BmvHoho.png[/img]

BTW, when someone runs `pod try AccordionSwift` the build fails since there's no Podfile or xcproj in the Examples/ folder.)

**Comment by Vkt0r** [comment]
@taberrr Thanks for reporting this. I'll be creating two tickets for each one of your issues.

**Comment by taberrr** [comment]
@Vkt0r Thanks for the fix & explanation! In the example project, I've updated Group A to look like this:

`let groupA: Parent<GroupCellModel, CountryCellModel> = Parent(state: .expanded, item: GroupCellModel(name: "Group A"), childs: [])` but now I'm getting a new Range error when I try tapping on the empty Parent row (I still want to be able to detect taps on the empty Parent.) ...

![Range error](https://i.imgur.com/wkkPPnT.png)

**Comment by taberrr** [comment]
I think I fixed it! I've updated .expanded and .collapsed cases to look like this:

```
        case .expanded:
            
            let numberOfChilds = item?.childs.count ?? 0
            if (numberOfChilds != 0) {
                let indexPaths = (currentPosition + 1...currentPosition + numberOfChilds)
                    .map { IndexPath(row: $0, section: indexPath.section)}
                
                tableView.deleteRows(at: indexPaths, with: .fade)
                dataSource.collapseChilds(atIndexPath: indexPath, parentIndex: parentIndex)
            }
            
        case .collapsed:
            
            let numberOfChilds = item?.childs.count ?? 0
            if (numberOfChilds != 0) {
                var insertPos = indexPath.row + 1
                
                let indexPaths = (0..<numberOfChilds)
                    .map { _ -> IndexPath in
                        let indexPath = IndexPath(row: insertPos, section: indexPath.section)
                        insertPos += 1
                        return indexPath
                }
                
                tableView.insertRows(at: indexPaths, with: .fade)
                dataSource.expandParent(atIndexPath: indexPath, parentIndex: parentIndex)
            }
        }```

**Comment by taberrr** [comment]
@Vkt0r Ohhh, I see why: the tag of the version in the .podspec (2.0.0) is pointing to commit af3033e (not the latest commit with your fixes) so you should probably bump it to 2.0.1 or something! :D

**Comment by taberrr** [comment]
@Vkt0r I'm back! Found another bug with this setup. 😮 After you tap a parent with no children, no other cells expand. Steps to repro:

1. Tap and expand Group B, then collapse it back down (works fine!)
2. Tap Group A (the empty group)
3. Tap Group B again (nothing happens)

**Comment by Vkt0r** [comment]
@taberrr That's a really good catch! Thanks for test the new version. #43 should fix the issue you found. 

I'll release a new version `2.0.1` very soon, just want to be sure no more bugs are found in the short term. You can point to `master` in the meantime using Cocoapods.

**Comment by taberrr** [comment]
@Vkt0r No problem! Thanks a bunch for the fix, it's looking great now!

**Comment by Vkt0r** [comment]
@taberrr `2.0.1` was released with all the above fixes. Thanks for reporting these.
