### ISSUE TITLE
Expanding last group doesn't show offscreen child rows

### ISSUE THREAD

**Issue by taberrr** [Vkt0r/AccordionSwift#45]
@Vkt0r I found a tiny UX situation using the latest Example project:

1. Tap "UITableViewController"
2. Scroll all the way to the end
3. Tap "Group H" to expand it

It seems that nothing happens, but the child rows actually _do_ get displayed, they're just off-screen. It would be nice to auto-scroll down so they're visible.

**Comment by Vkt0r** [comment]
@taberrr Thanks for reporting this again. Is this happening in the `UIViewController` example too?

**Comment by Vkt0r** [comment]
@taberrr #46 Should resolve this.
