### ISSUE TITLE
Accordion Swift Crashes "Library not loaded".

### ISSUE THREAD

**Issue by arishanapalli** [Vkt0r/AccordionSwift#48]
Just clone the project and run

Its crashes on loading the app on device 

dyld: Library not loaded: @rpath/AccordionSwift.framework/AccordionSwift
  Referenced from: /var/containers/Bundle/Application/B3A15C0F-880B-44C8-8EF9-62871F5AE81B/Example.app/Example
  Reason: image not found

Image not found, whats the image here missing?

**Comment by Vkt0r** [comment]
@arishanapalli Thanks for your report! It was fixed in #49.
