### ISSUE TITLE
Allow only one Parent Cell to be expanded at a time

### ISSUE THREAD

**Issue by DewaldDeJager** [Vkt0r/AccordionSwift#54]
This feature was requested in a previous version of the library. See Issue https://github.com/Vkt0r/AccordionSwift/issues/2.

## Issue Request
The framework should be customizable in such a way that a user of the framework should be able to configure a property and then the accordion will allow only one Parent Cell to be expanded at any time. This is very similar to many HTML/JS/CSS accordions.

## Possible Solutions
1. Before a parent is expanded, collapse all parent cells in the accordion
2. Keep track of the index of the expanded parent cell and when a different parent cell is expanded, toggle the previous parent cell

## Questions
1. Should the framework allow for no parents to be expanded as well?
2. If so, should the user be able to specify the initial state?

**Comment by Vkt0r** [comment]
If I remember correctly the second choice was the one I choose in the past when I added support for this behavior in the library. Please feel free to add it and I'll review it happily! If you go back to the 2.1.6 release I think this behavior was still there and it can help you as a reference if you want it. 

>Should the framework allow for no parents to be expanded as well?
Do you mean more than one level of expansion? Allowing children's cells to be the parent as well?

**Comment by DewaldDeJager** [comment]
> If you go back to the 2.1.6 release I think this behavior was still there and it can help you as a reference if you want it.

Did you mean release 1.2.6?

> Do you mean more than one level of expansion? Allowing children's cells to be the parent as well?

I meant should it be possible to have 0 parents expanded (All collapsed) would the implementation force strictly 1 parent to always be expanded? Just something to consider as different developers may want a different initial state.
